import type { UserRole } from '@prisma/client';

export const PERMISSIONS = {
  PDV_VIEW: 'pdv:view',
  PDV_SELL: 'pdv:sell',
  PDV_CANCEL: 'pdv:cancel',
  PDV_DISCOUNT: 'pdv:discount',
  PDV_CHANGE_PRICE: 'pdv:change_price',
  PDV_OPEN_CASH: 'pdv:open_cash',
  PDV_CLOSE_CASH: 'pdv:close_cash',
  PDV_SANGRIA: 'pdv:sangria',
  PDV_SUPPLY: 'pdv:supply',

  PRODUCT_VIEW: 'product:view',
  PRODUCT_MANAGE: 'product:manage',
  PRODUCT_DELETE: 'product:delete',
  PRODUCT_KIT: 'product:kit',
  PRODUCT_LABEL: 'product:label',

  STOCK_VIEW: 'stock:view',
  STOCK_MOVE: 'stock:move',
  STOCK_ADJUST: 'stock:adjust',
  STOCK_TRANSFER: 'stock:transfer',
  STOCK_INVENTORY: 'stock:inventory',

  CUSTOMER_VIEW: 'customer:view',
  CUSTOMER_MANAGE: 'customer:manage',
  SUPPLIER_VIEW: 'supplier:view',
  SUPPLIER_MANAGE: 'supplier:manage',

  SALE_VIEW: 'sale:view',
  SALE_RETURN: 'sale:return',
  QUOTE_VIEW: 'quote:view',
  QUOTE_MANAGE: 'quote:manage',

  PURCHASE_VIEW: 'purchase:view',
  PURCHASE_MANAGE: 'purchase:manage',
  PURCHASE_IMPORT_NFE: 'purchase:import_nfe',

  FINANCE_VIEW: 'finance:view',
  FINANCE_PAYABLE: 'finance:payable',
  FINANCE_RECEIVABLE: 'finance:receivable',
  FINANCE_CASH: 'finance:cash',
  FINANCE_BANK: 'finance:bank',

  REPORT_VIEW: 'report:view',

  USER_VIEW: 'user:view',
  USER_MANAGE: 'user:manage',

  SETTINGS_VIEW: 'settings:view',
  SETTINGS_MANAGE: 'settings:manage',

  PRINTER_VIEW: 'printer:view',
  PRINTER_MANAGE: 'printer:manage',

  AUDIT_VIEW: 'audit:view',
  BACKUP_MANAGE: 'backup:manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  ADMIN: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.PDV_VIEW, PERMISSIONS.PDV_SELL, PERMISSIONS.PDV_CANCEL, PERMISSIONS.PDV_DISCOUNT,
    PERMISSIONS.PDV_OPEN_CASH, PERMISSIONS.PDV_CLOSE_CASH, PERMISSIONS.PDV_SANGRIA, PERMISSIONS.PDV_SUPPLY,
    PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.PRODUCT_MANAGE, PERMISSIONS.PRODUCT_KIT, PERMISSIONS.PRODUCT_LABEL,
    PERMISSIONS.STOCK_VIEW, PERMISSIONS.STOCK_MOVE, PERMISSIONS.STOCK_ADJUST, PERMISSIONS.STOCK_INVENTORY,
    PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.CUSTOMER_MANAGE, PERMISSIONS.SUPPLIER_VIEW, PERMISSIONS.SUPPLIER_MANAGE,
    PERMISSIONS.SALE_VIEW, PERMISSIONS.SALE_RETURN, PERMISSIONS.QUOTE_VIEW, PERMISSIONS.QUOTE_MANAGE,
    PERMISSIONS.PURCHASE_VIEW, PERMISSIONS.PURCHASE_MANAGE, PERMISSIONS.PURCHASE_IMPORT_NFE,
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_PAYABLE, PERMISSIONS.FINANCE_RECEIVABLE, PERMISSIONS.FINANCE_CASH,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.USER_VIEW, PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.PRINTER_VIEW, PERMISSIONS.AUDIT_VIEW,
  ],
  CASHIER: [
    PERMISSIONS.PDV_VIEW, PERMISSIONS.PDV_SELL, PERMISSIONS.PDV_DISCOUNT,
    PERMISSIONS.PDV_OPEN_CASH, PERMISSIONS.PDV_SANGRIA, PERMISSIONS.PDV_SUPPLY,
    PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.SALE_VIEW, PERMISSIONS.QUOTE_VIEW,
  ],
  SELLER: [
    PERMISSIONS.PDV_VIEW, PERMISSIONS.PDV_SELL, PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.CUSTOMER_MANAGE, PERMISSIONS.QUOTE_VIEW, PERMISSIONS.QUOTE_MANAGE,
    PERMISSIONS.SALE_VIEW,
  ],
  STOCKIST: [
    PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.PRODUCT_MANAGE, PERMISSIONS.PRODUCT_LABEL,
    PERMISSIONS.STOCK_VIEW, PERMISSIONS.STOCK_MOVE, PERMISSIONS.STOCK_ADJUST, PERMISSIONS.STOCK_INVENTORY,
    PERMISSIONS.PURCHASE_VIEW, PERMISSIONS.PURCHASE_MANAGE, PERMISSIONS.PURCHASE_IMPORT_NFE,
    PERMISSIONS.SUPPLIER_VIEW, PERMISSIONS.SUPPLIER_MANAGE,
  ],
  FINANCIAL: [
    PERMISSIONS.SALE_VIEW, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_PAYABLE, PERMISSIONS.FINANCE_RECEIVABLE,
    PERMISSIONS.FINANCE_CASH, PERMISSIONS.FINANCE_BANK, PERMISSIONS.REPORT_VIEW,
  ],
};

export function hasPermission(role: UserRole, extra: string | null | undefined, perm: Permission): boolean {
  const base = ROLE_PERMISSIONS[role] ?? [];
  if (base.includes(perm)) return true;
  if (!extra) return false;
  try {
    const list = JSON.parse(extra) as string[];
    return list.includes(perm);
  } catch { return false; }
}